columns:
  - having_IP_Address: int64
  - URL_Length: int64
  - Shortening_service: int64
  - having_At_symbol: int64
  - double_slash_redirecting: int64
  - Prefix_suffix: int64
  - having_Sub_Domain: int64
  - SSLfinal_state: int64
  - Domain_registration_length: int64
  - Favicon: int64
  - port: int64
  - HTTPS_token: int64
  - Request_url: int64
  - URL_of_Anchor: int64
  - Links_in_tags: int64
  - SFH: int64
  - Submiting_to_email: int64
  - Abnormal_URL: int64
  - Redirect: int64
  - on_mouseover: int64
  - RightClick: int64
  - popUpWindow: int64
  - Iframe: int64
  - age_of_domain: int64
  - DNSRecord: int64
  - web_traffic: int64
  - Page_Rank: int64
  - Google_index: int64
  - Links_pointing_to_page: int64
  - Statistical_report: int64
  - Result: int64

numerical_columns:
  - having_IP_Address
  - URL_Length
  - Shortening_service
  - having_At_symbol
  - double_slash_redirecting
  - Prefix_suffix
  - having_Sub_Domain
  - SSLfinal_state
  - Domain_registration_length
  - Favicon
  - port
  - HTTPS_token
  - Request_url
  - URL_of_Anchor
  - Links_in_tags
  - SFH
  - Submiting_to_email
  - Abnormal_URL
  - Redirect
  - on_mouseover
  - RightClick
  - popUpWindow
  - Iframe
  - age_of_domain
  - DNSRecord
  - web_traffic
  - Page_Rank
  - Google_index
  - Links_pointing_to_page
  - Statistical_report
  - Result
